### ISSUE TITLE
The app is not stable for EPICGAMES under docker, it shouldn't be on the UNRAID APP section 

### ISSUE THREAD

**Issue by NeoMod** [Nackophilz/unraid_templates#10]
###  This template shouldn't be on the UNRAID APP section without proper warning

**The app is not stable under docker**, as per [#183](https://github.com/vogler/free-games-claimer/issues/183), and not just for EPIC GAMES but in general since **all the supported platforms have initiated countermeasures to block "headless" agents** from automatically redeem titles effectively.

In general I think it's misleading due to the numerous bugs it has, it shouldn't be posted on the "APP Section" where users with minimal knowledge usually find templates for apps that work almost *out-of-the-box". 

Besides the obvious problems, **this template should also come with a big warning** to inexperienced docker users to avoid it since they **might risk getting banned from the stores** due to illicit activities thus **losing even the paid titles** they might have in library.

**Comment by Nackophilz** [comment]
Good evening NeoMod, indeed, I thought that the last big update had corrected the problem of Epic Games, I will remove the template until it stabilizes.
