### ISSUE TITLE
Incorrect template format

### ISSUE THREAD

**Issue by CorneliousJD** [Nackophilz/unraid_templates#2]
I PM'd you on unraid forums, but the appdata directory formatting is incorrect (try to install from CA and you'll see what I mean)

Also you're missing the PG OTP code option as well.

![image](https://user-images.githubusercontent.com/724777/221029382-4cdc501e-f2dc-4d3c-980f-c85df0268339.png)

**Comment by Nackophilz** [comment]
Hi @CorneliousJD!

I updated the template to correct this part normally :)

Concerning the PG OTP, I add it, I didn't pay attention to it when I created the template ;)

I also add the PG REDEEM option
