### ISSUE TITLE
[request] Implement store selection

### ISSUE THREAD

**Issue by nodiaque** [Nackophilz/unraid_templates#4]
Hello,

It would be freat if we could enable/disable store we want/don't need. This feature already exist in the original project.

https://github.com/vogler/free-games-claimer/issues/78

An easy way would be to simply change the entrypoint script. Then in the script, you get a var like STOREVAR where you append each store one by one depending on if the var is true.

**Comment by nodiaque** [comment]
for more info, for now, the way I do it is by adding this in "post argument"
bash -c "node epic-games.js; node gog.js"

**Comment by Nackophilz** [comment]
Hi ! 
As i answer on the issue , the only way to do it for now is the line in post arguments ( as you Can see in the description of the template) , i suggested to make some variables ( you point on my comment on the #73) 
I dont think he already implement it , try if u want but i dont think

**Comment by x3rt** [comment]
Apologies for hijacking this Closed issue, but I cannot find "Post Arguments" anywhere.

**Comment by Nackophilz** [comment]
Hi, you have to enable advanced on your template :)
