### ISSUE TITLE
Container stops itself after running

### ISSUE THREAD

**Issue by raybun** [Nackophilz/unraid_templates#5]
After I leave the `free-games-claimer` container running for a while, it seems to stop itself (can't see a reason for that in the logs) and I have to start it manually. Is that the intended behaviour, or should it continue running?

**Comment by Nackophilz** [comment]
Hi @raybun, yes, that's normal, that's how it works, we've already talked to the creator of the image, for the moment, he has no plans to include a cron inside it.. :/

What I can advise you is to install the userscripts plugin, and to add this script that I made for myself to run every X hours:

`
#!/bin/bash
docker start free-games-claimer
while ! docker inspect -f {{.State.Running}} free-games-claimer | grep -q true; do sleep 1; done

`

Then you schedule it, myself i scheduled this script every 24h :)
