### ISSUE TITLE
How to schedule  free-games-claimer in Unraid?

### ISSUE THREAD

**Issue by sero2kk** [Nackophilz/unraid_templates#7]
hi,

is there any way to schedule free-games-claimer in Unraid?

greetz

**Comment by eeagle** [comment]
It's easy.

You need the PlugIn "User Scripts" (https://forums.unraid.net/topic/48286-plugin-ca-user-scripts/), then go to `Settings` > `USER SCRIPTS` > `Add New Script` with the following Content:
```sh
#!/bin/bash
docker restart free-games-claimer
```
then `Scheduled daily` - that's it ;-)

**Comment by sero2kk** [comment]
thx
