### ISSUE TITLE
New version is out and hasnt been implemented in template

### ISSUE THREAD

**Issue by Zepius** [Nackophilz/unraid_templates#9]
A new version is out that fixes an issue with unsolvable captchas for epic. it was released end of December, but logs show the unraid template is using the one from November.

![image](https://github.com/Nackophilz/unraid_templates/assets/50144836/aa317c51-034c-4071-8323-6a42f33053f9)

https://github.com/vogler/free-games-claimer/releases/tag/v1.6

**Comment by Nackophilz** [comment]
Add ghcr.io/vogler/free-games-claimer:main to repo for your template, or reinstall Free game and choose the main branch

Just updated the template to add 'ghcr.io/vogler/free-games-claimer:main' by default.

**Comment by Zepius** [comment]
that fixed it.
